### ISSUE TITLE
Please upload the models to Huggingface

### ISSUE THREAD

**Issue by Subarasheese** [nick8592/text-guided-image-colorization#1]
Hello,

The URLs provided to download the pretrained model weights are from an unconventional website, and download speeds are very slow, and I had the download failing due a connection timeout, and had to start over.

Please consider uploading the pretrained weights to the Huggingface website, specifically:

* sdxl_light_caption_output
* sdxl_light_custom_caption_output

Thank you

**Comment by nick8592** [comment]
Hi,

I appreciate your feedback on the download issues with the pretrained model weights. I will upload these models to Hugging Face as soon as possible.

**Comment by nick8592** [comment]
I've updated the installation instructions to include a link to Hugging Face. You can check it out [here](https://github.com/nick8592/text-guided-image-colorization?tab=readme-ov-file#installation).
